name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite disparar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar QEMU para emulación
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Configurar buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Loguearse en el registro
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}


      # 5. Build y push multi-arch
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cibarraleonel/multiarch:latest

